### PR TITLE
Apply [dotnet-format](https://github.com/dotnet/format)

### PR DESCRIPTION
**Pull request by hanabi1224**
##### You need to complete

Apply [dotnet-format](https://github.com/dotnet/format)

### CODE REVIEW

**Comment by doublnt** [comment]
Our product code is generated by code generator. The format problem should be update and fix by updating generator code. Thanks for pull a request.

**Comment by hanabi1224** [comment]
@doublnt Ah, got it. It would be great to apply dotnet official formatting to this repo tho,  plz checkout https://github.com/dotnet/format

**Comment by doublnt** [comment]
@hanabi1224  We will apply this code format in our code generator in our next version, but it might not be will soon, thanks for your advice.

**Comment by hanabi1224** [comment]
@doublnt  My pleasure : )

**Pull request closed without merging**
